name: wheel-seminar-CD

on:
  push:
    branches:
      - main

jobs:
  cd:
    strategy:
      matrix:
        platform: [amd64, arm64]

    name: Deploy to Docker Hub for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kmc7468/wheel-seminar-cicd:${{ github.sha }}_${{ matrix.platform }}, kmc7468/wheel-seminar-cicd:latest_${{ matrix.platform }}
          platforms: linux/${{ matrix.platform }}